version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    env_file:
      - '.env'

volumes:
  postgres:
